### ISSUE TITLE
Support for network 2.8.x?

### ISSUE THREAD

**Issue by peti** [haskell/HTTP#120]
Will you release an update that supports current versions of `network`?

http://packdeps.haskellers.com/feed?needle=exact:HTTP

**Comment by hsenag** [comment]
Sorry, I've been getting a bit behind on maintenance, I'll get this sorted out in the next few days.

I understand that `network` is planning on dropping some old functions that `HTTP` still relies on in order to support older versions, which makes me nervous about each major update, but I just checked 2.8 and it looks like it hasn't happened yet.

`Win32` is also awkward because there were some confusing changes to the registry API I haven't figured out yet, but that shouldn't obstruct a `network` update.

**Comment by hsenag** [comment]
I've updated the network bounds on hackage. I'm keeping this open till I actually update the repo - I need to remind myself how to sync that from hackage cleanly.

**Comment by hsenag** [comment]
This is done now (or rather was done some time ago)
